sigstore/sigstore-python

setup.py
sigstore/_internal/fulcio/_client.py

Implement Fulcio client API

---

sigstore/_verify.py

Verify that timestamp is before the signing certificate expiry

---

.github/workflows/ci.yml
CONTRIBUTING.md
Makefile
README.md
setup.py

README: fill in details

---

CODEOWNERS
CONTRIBUTING.md
COPYRIGHT.txt
README.md
setup.py
sigstore/__main__.py
sigstore/_cli.py
sigstore/_internal/fulcio/_client.py
sigstore/_internal/merkle.py
sigstore/_internal/oidc.py
sigstore/_internal/rekor/_client.py
sigstore/_internal/sct.py
sigstore/_internal/set.py
sigstore/_sign.py
sigstore/_verify.py
sigstore/_version.py
test/test_sign.py
test/test_store.py
test/test_verify.py
test/test_version.py

Signed-off-by: Luke Hinds <lhinds@redhat.com>

Migrate repo fields / governance to sigstore

---

README.md
sigstore/_cli.py
sigstore/_sign.py
sigstore/_verify.py

cli, sign, verify: sign and verify multiple files at once

---

.bandit.yaml
.github/workflows/ci.yml
setup.py

Resolves: #51
Signed-off-by: Luke Hinds <lhinds@redhat.com>

Implement Bandit CI Tests

---

sigstore/_cli.py
sigstore/_sign.py
sigstore/_verify.py

Fixes some side effects revealed by #49.

sigstore: prevent unintended I/O side effects

---

README.md
sigstore/_version.py

Another prerelease to push out MVP changes/work out kinks ahead of #47.

version: 0.0.1-pre.2

---

setup.py
sigstore/_cli.py
sigstore/_internal/oidc.py
sigstore/_verify.py

This PR adds support for signing via OAuth/browser flow. At the moment it only supports tokens issued via the `auth.sigstore.dev` issuer but it'll be easy to extend this in a follow up PR.
Fixes #41
```release-note
* Added support for signing via OAuth flow
```

Support OAuth flow for signing

---

README.md
sigstore/_cli.py

cli: add a flag for disabling ambient OIDC detection

---

.github/workflows/ci.yml
MANIFEST.in
Makefile
pyproject.toml
setup.py

~~This requires a `MANIFEST.in`, since `setuptools` apparently
can't specify package data in `pyproject.toml`. Yet.~~
Closes #69.

build: move almost everything to pyproject.toml

---

mypy.ini
sigstore/_cli.py
sigstore/_verify.py
test/test_verify.py

Similar to the refactor in #65.

cli, verify: refactor, add logging

---

sigstore/_internal/fulcio/__init__.py
sigstore/_internal/fulcio/_client.py
sigstore/_sign.py

fulcio, _sign: Request certificates via CSR

---

sigstore/_internal/fulcio/__init__.py
sigstore/_internal/fulcio/_client.py
sigstore/_sign.py

This is a temporary reversion of #74, until CSRs hit Fulcio prod.

Revert "fulcio, _sign: Request certificates via CSR (#74)"

---

pyproject.toml

We haven't tested with anything earlier.

pyproject: pin pyjwt>=2.1

---

sigstore/_version.py

Will cut a tag and publish on merge.

version: 0.4.0

---

README.md
sigstore/_cli.py

Adds a `--version` flag to help us with debugging.

sigstore, README: add `--version` flag

---

.github/workflows/release.yml

workflows/release: smoke-test each distribution

---

sigstore/_version.py

So that we can upload a new set of distributions to PyPI.

version: 0.4.1

---

sigstore/_internal/oidc/__init__.py
sigstore/_internal/oidc/ambient.py
test/internal/oidc/test_ambient.py

Adds ambient credential detection for Google Cloud. Towards #31.

Google Cloud ambient credential detection

---

sigstore/_internal/oidc/oauth.py

oauth: Fix race in OIDC token retrieval

---

README.md
sigstore/_cli.py
sigstore/_internal/oidc/__init__.py
sigstore/_internal/rekor/client.py
sigstore/_sign.py
sigstore/_verify.py

_cli, _sign, _verify, oidc: Add `--fulcio-url` and `--rekor-url`

---

sigstore/_verify.py

We don't currently use these, but we probably will in the future.

sigstore/verify: add more sigstore extension OIDs

---

README.md

This should help with questions of the sort raised in #126.

README: add signing examples

---

.github/workflows/staging-tests.yml
README.md
sigstore/_cli.py

`sigstore verify`: support multiple inputs

---

sigstore/__init__.py

sigstore: 0.6.0

---

.github/workflows/staging-tests.yml

workflows/staging-tests: open an issue on failure

---

sigstore/_internal/fulcio/client.py

I'm assuming that `make lint` is broken since this change made its way into `main` without breaking PR testing. I'm looking into this now.

fulcio: Fix lint

---

Makefile

Makefile: Make `lint` exit non-zero with unstaged changes

---

.github/workflows/ci.yml
sigstore/_cli.py
sigstore/_internal/oidc/ambient.py

oidc, _cli: Add more detailed error messages when ambient credential detection fails in GitHub Actions

---

README.md
sigstore/__init__.py

Just to get the fix in #173 out the door.

Bump to 0.6.3

---

.github/workflows/scorecards-analysis.yml

Signed-off-by: Azeem Shaikh <azeemshaikh38@gmail.com>
v2:alpha has some bug fixes
NONE
NONE

Update scorecard-action to v2:alpha

---

sigstore/__init__.py

sigstore: 0.6.4

---

sigstore/__init__.py

sigstore: 0.6.5

---

Makefile

Makefile: run recursive make silently

---

.github/workflows/ci.yml
sigstore/_internal/rekor/client.py
sigstore/_verify.py
test/test_sign.py

Tests: ensure consistency of transparency log response and entry

---

sigstore/_internal/rekor/client.py
sigstore/_verify.py

~~WIP; needs cleanup.~~
Fixes #237.

rekor, verify: replace unstable API use

---

sigstore/_cli.py
sigstore/_verify.py

_verify: make the failure reason more detailed when rekor lookup fails

---

sigstore/__init__.py

sigstore: 0.6.7

---

README.md
sigstore/_cli.py

This rounds out the envvar changes in #242.

_cli: add boolean envvar defaults

---

sigstore/__init__.py

sigstore: 0.6.8

---

.github/workflows/ci.yml
pyproject.toml

I don't think I have permission to modify branch protections anymore, so someone else will need to do that.

workflows/ci: add Python 3.11 to matrix

---

README.md
sigstore/_cli.py
sigstore/_verify.py

Support `--cert-identity`

---

.github/workflows/scorecards-analysis.yml

scorecards-analysis: bump scorecard-action to 2.0.6

---

.bump

This wasn't being used, and referenced an old file anyways.

.bump: delete

---

.github/dependabot.yml

dependabot: Setup Dependabot for GitHub Actions

---

sigstore/__init__.py

sigstore: 0.8.0

---

.github/workflows/release.yml
sigstore/__init__.py

sigstore: 0.8.2

---

.github/workflows/release.yml
sigstore/__init__.py

https://www.youtube.com/watch?v=UBarc_-Eoek

sigstore: 0.8.3

---

Makefile

This ensures the venv that's required for these commands actually exists.

Add makefile targets on venv

---

sigstore/_internal/oidc/__init__.py
sigstore/_internal/oidc/ambient.py
sigstore/_internal/oidc/issuer.py
sigstore/_sign.py
sigstore/_utils.py
test/unit/internal/oidc/test_ambient.py

This just brings out docstring coverage up a bit more. I've focused on still-private APIs that we expect to eventually be public.

Chore: More docs

---

test/unit/internal/oidc/test_ambient.py
test/unit/internal/oidc/test_issuer.py
test/unit/internal/test_ctfe.py
test/unit/verify/test_policy.py

closes #28.
increased coverage in:
- `sigstore/_internal/oidc/issuer.py`
- `sigstore/_internal/oidc/ambient.py`
- `sigstore/_internal/ctfe.py`
- `sigstore/_verify/policy.py`

TASK(jl): increase code coverage.

---

.github/workflows/conformance.yml

Doing this from a fork, to confirm that it works as expected.

workflows/conformance: bump sigstore-conformance action

---

sigstore/_internal/oidc/oauth.py
sigstore/_internal/rekor/client.py

See #14.
Current coverage:
```
========= Coverage for /Users/william/devel/sigstore-python/sigstore/ ==========
----------------------------------- Summary ------------------------------------
| Name                             |    Total |    Miss |    Cover |    Cover% |
|----------------------------------|----------|---------|----------|-----------|
| __init__.py                      |        1 |       0 |        1 |      100% |
| __main__.py                      |        1 |       0 |        1 |      100% |
| _sign.py                         |        7 |       0 |        7 |      100% |
| _utils.py                        |        9 |       0 |        9 |      100% |
| _internal/__init__.py            |        1 |       0 |        1 |      100% |
| _internal/ctfe.py                | …
```

docs: more docstring coverage

---

Makefile
sigstore/_internal/fulcio/client.py
sigstore/_internal/tuf.py

Makefile, sigstore: round out doc coverage, enable interrogate

---

README.md
test/unit/test_sign.py

Just mopping up a few small things.

Miscellaneous cleanup

---

sigstore/_internal/tuf.py

Just some small cleanup tasks.

tuf: intrinsic types, use `urljoin`

---

.github/workflows/docs.yml

workflows: Add workflow for generating and deploying API docs

---

.github/dependabot.yml
pyproject.toml

pyproject: constrain ruff

---

.github/workflows/ci.yml
.github/workflows/conformance.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/staging-tests.yml

This should speed our workflows up significantly.

workflows: use pip cache

---

CHANGELOG.md
sigstore/__init__.py

One last release before 1.0, to give bugs a chance to shake out.

Prep 0.10.0

---

.github/workflows/docs.yml

workflows: Simplify documentation deployment workflow

---

README.md

README: ToC, cleanup

---

CHANGELOG.md

CHANGELOG: catchup

---

CHANGELOG.md
sigstore/_cli.py
sigstore/verify/__init__.py
sigstore/verify/verifier.py

sigstore: `RekorEntryMissing` -> `LogEntryMissing`

---

pyproject.toml

pyproject: add API documentation link to metadata

---

sigstore/__init__.py

Shaking things out before 1.0!

sigstore: 1.0.0rc1

---

CHANGELOG.md
sigstore/_internal/tuf.py
test/unit/conftest.py

sigstore, test: relax timeout on TUF retrieval

---

.gitattributes
.github/workflows/ci.yml
.github/workflows/lint.yml
Makefile
test/unit/conftest.py
test/unit/internal/test_tuf.py

~~WIP, just seeing how annoying this will be.~~
Closes #417.

Makefile, ci: test Windows, accomodations

---

.github/workflows/release.yml

s/diretories/directories
This was found while using sigstore python and the github actions in our own project. Thank you so much for such a great product.
Signed-off-by: Rob Ankeny <ankenyr@gmail.com>
None
-->
None

Fixing typo in release.yml

---

CHANGELOG.md

CHANGELOG: record changes

---

sigstore/_internal/oidc/__init__.py
sigstore/sign.py

Found this to be helpful for debugging.

Log cert-identity and cert-oidc-issuer at signing time

---

.github/workflows/conformance.yml
sigstore/_cli.py

Broken out from #484.
These changes won't fix the suite until they land on `main`, unfortunately.

Conformance suite fixes

---

sigstore/_internal/oidc/ambient.py

Caught this when breaking this out into a separate library.

Use DEFAULT_AUDIENCE instead of hard-coding

---

sigstore/__init__.py

sigstore: 1.1.0rc1

---

CHANGELOG.md
sigstore/__init__.py

Prep 1.1.1

---

pyproject.toml
sigstore/verify/models.py
sigstore/verify/verifier.py

See failures in #525 and #518.

MyPy 1.1, fixes

---

sigstore/__init__.py

Kicking the tires on the requirements pinning workflow :)

sigstore: 1.1.2rc1

---

.github/workflows/pin-requirements.yml

fixes typo in pin-requirements :)

workflows/pin-requirements: typo

---

.github/workflows/pin-requirements.yml

workflows/pin-requirements: fix interpolation

---

sigstore/_internal/sct.py
test/unit/test_sign.py

Fixes an online OIDC test regression.

sigstore, test: reflow, fix

---

.github/workflows/pin-requirements.yml

#572: see https://github.com/sigstore/sigstore-python/actions/runs/4472434361

workflows/pin-requirements: fix job name

---

CHANGELOG.md
sigstore/__init__.py

This gets the staging root changes out the door.

release: prep 1.1.2

---

CHANGELOG.md

CHANGELOG: fix link

---

CHANGELOG.md
sigstore/_internal/tuf.py
test/unit/internal/test_tuf.py

tuf: remove non-trusted-root handling paths

---

.github/workflows/conformance.yml

Now with no labelling required!

workflows: bump sigstore-conformance

---

test/integration/sigstore-python-conformance

Bump the `sigstore-python-conformance` runner to mirror the [upstream](https://github.com/sigstore/sigstore-conformance/blob/main/sigstore-python-conformance).

conformance: bump runner

---

README.md

Documentation updated to follow the default behavior of the `sigstore` CLI.

doc: README document the (now default) `.sigstore` bundles

---

.github/dependabot.yml

This reverts commit 09615c574b2dcfe666740f2b998d89bc6be007cb.

Revert "Try separate config for /install directory (#742)"

---

.github/workflows/pin-requirements.yml

This allows us to manually re-run the workflow without having to copy/paste the latest tag into the input.

Update `pin-requirements.yml` to use latest tag as default

---

CHANGELOG.md

Forgot to suggest this with that PR.

CHANGELOG: record #745

---

sigstore/_internal/fulcio/client.py
sigstore/oidc.py
sigstore/transparency.py
test/unit/internal/fulcio/test_client.py

Replace deprecated pydantic uses (removing the deprecation warnings from test suite output).
Fixes #741
NONE
-->
NONE

Pydantic fixes

---

SECURITY.md

It's already set at the org level, and we want to discourage each repo setting its own security policy. It will be accessible at https://github.com/sigstore/sigstore-python/security/policy

Remove security policy

---

sigstore/__init__.py

See #766; I don't think we have anything else queued up, so I figure there's nothing stopping the RC 🙂

sigstore: 2.0.0rc3

---

sigstore/_utils.py
sigstore/verify/verifier.py

These linter errors appeared first in https://github.com/sigstore/sigstore-python/pull/790  workflow run

Tweak some ignore-hints to make mypy 1.6 happy

---

CHANGELOG.md
sigstore/__init__.py

prep 2.0.1

---

sigstore/_cli.py
sigstore/_internal/fulcio/client.py
sigstore/_internal/sct.py
sigstore/_internal/trustroot.py
sigstore/_utils.py
sigstore/verify/verifier.py
test/unit/internal/test_trust_root.py

It intends to close #886
We don't have sct verification for the certificate during the verification, only for sign. These PR implements sct verification for verifying flow.
cc @jku

Adding sct verification for certificates on verify flow

---

sigstore/_internal/trustroot.py

Closes #925
The PR #910 modified the function for retuning all keys instead of the active keys. It should return a generator but the PR made return a list.
This PR makes the function return a generator with all keys by allowing expired keys on `_is_timerange_valid` function.

fix: rollback code for return generator allowing expired keys

---

sigstore/verify/verifier.py

verifier: set store flags explicitly

---

sigstore/sign.py
test/unit/test_sign.py

We need the inner proto type here.

sign: fix envelope type

---

.github/workflows/release.yml
CHANGELOG.md
sigstore/__init__.py

**This is for series/2.1.x**
* 2.1.4 release failed
* Fix issue by backporting slsa action update
* Attempt again with 2.1.5

Backport slsa upgrade

---

CHANGELOG.md
sigstore/sign.py
test/unit/test_sign.py
test/unit/verify/test_verifier.py

rename sign_intoto -> sign_dsse

---

sigstore/__init__.py

This is an RC release, so no changelog or other metadata changes besides the version are required.
CC @facutuesca

sigstore: 3.0.0rc1

---

sigstore/__init__.py

Another RC release, no changelog or other metadata changes besides the version are required.
cc @woodruffw

sigstore: 3.0.0rc2

---

CHANGELOG.md
sigstore/__init__.py

sigstore: 3.0.0

---

CHANGELOG.md
sigstore/__init__.py

prep 3.1.0

---

pyproject.toml

Add Python 3.12 classifier to pyproject.toml

---

sigstore/oidc.py

These lines are present a few lines above

Remove duplicated constants in oidc.py

---

CHANGELOG.md
sigstore/__init__.py

Preps 3.6.0 to get #1247 out the door.

prep 3.6.0

---

sigstore/verify/verifier.py

As pointed out by @facutuesca.

docs: clarify Verifier APIs

---

README.md

docs: added a link to the CI workflow

---

pyproject.toml
sigstore/verify/verifier.py
test/unit/verify/test_verifier.py

chore(deps): bump rfc3161-client to >= 1.0.3

---

CHANGELOG.md
sigstore/__init__.py

chore: prep 3.6.4

---

CHANGELOG.md
sigstore/__init__.py

* I rewrote the changelog to make it hopefully more useful to users, combined related items and tweaked many descriptions 
* also added the 3.6.5 entry to changelog
Fixes #1465

Prepare 4.0.0 release
