sigstore/sigstore-python

- .github/workflows/ci.yml
We don't need to run this for every Python version.
> Make linting a separate job

- setup.py
- sigstore/_internal/fulcio/_client.py
- sigstore/_internal/oidc.py
This PR provides an `Identity` class which supports all the OIDC issuers Fulcio currently supports, as well as determine alternative proofs (e.g. using the `subject` claim instead of `email` for GitHub Actions)
Fixes #17.
> Support multiple issuers and alternative proofs

- .github/workflows/release.yml
This adds a release workflow for automating the creation of GitHub and PyPI releases whenever we release a new version of `sigstore-python`.
> github/workflows: add release workflow

- sigstore/_cli.py
- sigstore/_internal/oidc/__init__.py
- sigstore/_internal/oidc/ambient.py
- sigstore/_internal/oidc/oauth.py
- test/internal/oidc/test_ambient.py
Refactors `sigstore._internal.oidc` into a structured (directory) module and adds `sigstore._internal.oidc.ambient` for ambient credential detection. See #31.
See #31. Does not close, since other detectors are needed.
> internal/oidc, test: ambient credentials, refactoring

- .github/workflows/release.yml
- sigstore/_cli.py
- sigstore/_internal/oidc/ambient.py
- test/internal/oidc/test_ambient.py
This change hooks up the ambient credential detection to the CLI and uses it to sign releases in Github Actions.
See https://github.com/sigstore/sigstore-python/issues/31. Does not close, since other detectors are needed.
> Sign releases with ambient credentials via Github Actions

- setup.py
- sigstore/__init__.py
- sigstore/_cli.py
- test/test_sign.py
- test/test_verify.py
This also required some changes to the top-level `__init__.py`, to avoid importing runtime dependencies by default. We haven't stabilized a public API yet, so this shouldn't be a problem.
> setup: use importlib instead of exec

- sigstore/_cli.py
- sigstore/_sign.py
- test/test_sign.py
This is just general refactoring: it adds use of `logging` in the CLI and signing modules, and makes `sign` return a `SigningResult` for eventual rendering instead of plumbing `click.echo` through a non-CLI API.
> Refactor: add logging, better isolate output

- sigstore/_internal/rekor/_client.py
- sigstore/_sign.py
This fixes a small bug where we were publishing the public key with the Rekor entry instead of the signing certificate (which includes the public key).
(cc @eddiezane)
> Publish cert to Rekor instead of pubkey

- README.md
- sigstore/_cli.py
- sigstore/_internal/oidc/__init__.py
- sigstore/_internal/oidc/issuer.py
- sigstore/_internal/oidc/oauth.py
- sigstore/_sign.py
Signed-off-by: Alex Cameron <asc@tetsuo.sh>
This PR adds support for configurable OIDC issuers. An `oidc-issuer` flag has been added for this purpose. `sigstore` will query the issuer's `.well-known/openid-configuration` to find its endpoints and then use them to retrieve an OIDC token. The following flags have also been exposed since they need to be customised on a per issuer basis:
- `oidc-client-id`
- `oidc-client-secret`
> Support configurable OIDC issuers

- pyproject.toml
- sigstore/__init__.py
This will hopefully fix some of the distribution strangeness we're seeing.
> pyproject, sigstore: use flit as our build backend

- sigstore/_internal/oidc/ambient.py
Adds the specific false positive, so that we don't accidentally mask others.
> oidc/ambient: constrain nosec

- README.md
- cloudbuild.yaml
- sigstore/_internal/oidc/ambient.py
- test/internal/oidc/test_ambient.py
As a follow-on to #88, and towards #31, support service account impersonation, which makes it possible to use Google Cloud Build.
Also adds documentation for ambient credential detection.
> Support Google Cloud impersonation

- sigstore/_internal/fulcio/__init__.py
- sigstore/_internal/fulcio/client.py
- sigstore/_internal/sct.py
- test/internal/fulcio/__init__.py
- test/internal/fulcio/test_client.py
This replaces `FulcioSignedCertificateTimestamp` with `FulcioSCT`,
which inherits from `pydantic.BaseModel` and uses pydantic's
verification APIs instead of doing all verification ad-hoc in
the constructor.
The relationship to `cryptography.x509.SignedCertificateTimestamp`
is maintained via virtual subclassing.
This should make testing detached SCTs much easier. Marking as a draft until I add some corresponding tests.
> _internal/fulcio: refactor SCT model

- sigstore/_internal/oidc/ambient.py
- test/internal/oidc/test_ambient.py
This prevents an overzealous error when detecting ambient Google Cloud credentials. The root cause is that many vendors use the DMI/SMBIOS table to pass around product information; unexpected data here is a sign of the wrong host rather than an erroneous state on the right host.
Fixes #97.
> oidc/ambient: Google: fail softly if the SMBIOS product name doesn't match

- .github/workflows/staging-tests.yml
- README.md
- pyproject.toml
- sigstore/_cli.py
- sigstore/_internal/rekor/client.py
- sigstore/_sign.py
- sigstore/_verify.py
This addresses the greedy output flags problem by giving them mandatory values, and adding a new option (`--output`) that toggles whether default output filenames are used instead.
It also addresses #123 by adding a new `--force` option that, if not passed, will refuse to continue with `sigstore sign` until pre-existing signing artifacts are moved or deleted from the overwriting path(s).
More generally, this PR refactors the entire `sigstore` CLI to use Python's default `argparse` instead of `click`. The primarily reason for this is to avoid `click`'s ambiguities around greedy value captures (https://github.com/pallets/click/issues/2307), but it'll also help us move towards a configuration model as part of #124.
Fixes #122.
Fixes #123.
> CLI: Add `--output` and `--force`

- .github/workflows/staging-tests.yml
- README.md
- sigstore/_cli.py
This removes the `--output` file and makes its previous behavior the default, to prevent ambiguous argument lines like `sigstore sign --output input.ext`. 
The old default behavior can be re-enabled by passing `--no-default-files`. Open to suggestions on a better flag name 🙂 
> cli: replace `--output` with `--no-default-files`

- sigstore/_internal/oidc/oauth.py
~~WIP.~~
~~This adds more debug logs and adds the `SIGSTORE_OAUTH_BROWSER` environment variable, which can be used to override the `webbrowser`'s default browser selection (e.g. `SIGSTORE_OAUTH_BROWSER=firefox`).~~
Removed the `SIGSTORE_OAUTH_BROWSER` variable, since it's essentially a duplicate of what `webbrowser` already does via the `BROWSER` variable. Instead, this PR adds `SIGSTORE_OAUTH_FORCE_OOB`, which forcefully disables the in-band OAuth flow if set.
See #96.
> OAuth: more debug logs, configurable browser

- sigstore/_internal/oidc/oauth.py
> oauth: use a context manager for the server's thread

- pyproject.toml
I noticed when testing in Github Actions that `sigstore-python` is incompatible with `cryptography` versions earlier than 3.1 because the API is designed to take different arguments.
> pyproject.toml: Pin `cryptography` to >= 3.1 to avoid incompatibilities

- README.md
- sigstore/_cli.py
Just something I noticed when working on a Github Action for `sigstore-python`.
> _cli: Remove references to removed `--output` flag

- sigstore/_internal/fulcio/client.py
The main differences are:
* RootCert -> TrustBundle now returns a list of chains
* SigningCertificate differentiates between the embedded and detached
SCT, and it's no longer returned in a header.
* Support for gRPC, but this continues to use HTTP.
No changes necessary for the request construction, `CertificateSigningRequest` is still the name of the field on the request.
Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>
> Switch to Fulcio v2 API

- pyproject.toml
> pyproject: remove 'pem' dependency

- CONTRIBUTING.md
- Makefile
This follows the same pattern as Warehouse, and splits `make lint` into two separate targets:
* `make lint`: Run all linters, exiting with nonzero if any fail
* `make reformat`: Run the subset of linters that can automatically rewrite the source
Closes #169.
> Tweak linting target

- sigstore/_verify.py
> _verify: Create a new `X509Store` for each `verify` call

- .github/workflows/staging-tests.yml
- sigstore/_verify.py
…fied entry
Signed-off-by: Asra Ali <asraa@google.com>
Part of https://github.com/sigstore/sigstore-python/issues/184
* Adds log level `DEBUG` to CI staging tests to allow for detection of problems in case something goes wrong with staging.
* Adds an debug log output in `verify` for the `log_index` of the verified entry, to match with parity on `sign`.
> ci: add debug loglevel to ci and debug log of verified log index

- README.md
pip can download the file automatically, so the curl call is not needed. Unless you trust curl more than requests, which I guess is not entirely unreasonable :)
Close #191.
> Skip curl to download requirements.txt

- pyproject.toml
- sigstore/_internal/fulcio/client.py
- sigstore/_internal/rekor/client.py
- sigstore/_internal/sct.py
- sigstore/_sign.py
- sigstore/_verify.py
- test/internal/fulcio/test_client.py
This brings a couple of new (and much-needed) SCT APIs, allowing us to remove a variety of nasty unpacking hacks.
Closes #195.
Closes #142.
> treewide: upgrade to cryptography 38

- sigstore/_internal/fulcio/client.py
- sigstore/_internal/rekor/client.py
> _internal: Rekor and Fulcio clients clean up their HTTP sessions on release

- sigstore/_internal/oidc/ambient.py
- sigstore/_internal/rekor/client.py
Just a small QoL improvement: this prevents us from over-accepting inputs to these models, since Pydantic is happy to coerce fields into their correct types without `StrictFoo`.
> sigstore: use stricter pydantic fields, where applicable

- pyproject.toml
Without this, environments that already have `pyOpenSSL` installed are likely to reuse that version, causing breakages when we directly or indirectly (via `cryptography`) use more recent APIs. 
In particular, the lack of a constraint here caused some failures in `gh-action-sigstore-python`: https://github.com/trailofbits/gh-action-sigstore-python/issues/25
> deps: constrain pyOpenSSL to >=22.0.0

- README.md
Now that we've migrated `gh-action-sigstore-python` to the Sigstore org.
> README: update GitHub Action slugs

- .github/pull_request_template.md
- CONTRIBUTING.md
Signed-off-by: Diogo Teles Sant'Anna <diogoteles08@gmail.com>
This PR was created because the Template for creating a PR have a text that says it's necessary to have all commits signed-off to make the PR, but it was not said on the CONTRIBUTING.md.
IMPORTANT: on the PR template it's still present the item "lastly, ensure there are no merge commits!". If this step is not necessary anymore, it would be better to have it removed. I could not find where to change this text, so I supposed it was configured directly on github. Let me know if I can help with this as well.
> Update CONTRIBUTING.md to expose the requirements to open a PR. Closes #224

- README.md
- sigstore/_cli.py
This PR adds a subcommand `get-identity-token` that allows the user to get an identity token which can be used with the `sign` command's `--identity-token` flag.
> Add a get-identity-token subcommand

- .github/workflows/release.yml
- README.md
This reverts commit e5acd696f1337e54b305b90b9951f47a9be7c34c due to https://github.com/slsa-framework/slsa-github-generator/issues/942, since it's blocking releases.
We can un-revert this once a new version of that action is released.
(FYI @diogoteles08)
> Revert "Add SLSA provenance generator to release; closes #222 (#223)"

- sigstore/_cli.py
This doesn't add envvars for boolean flags (like `--staging`), but it does for nearly all options that take values.
> _cli: add envvar defaults for most options

- test/conftest.py
- test/test_sign.py
> test: add an `ambient_oidc` marker

- .github/workflows/depsreview.yml
Per https://github.com/sigstore/TSC/issues/34 moving to a common workflow across projects
Signed-off-by: Bob Callaway <bcallaway@google.com>
> add community-wide reusable workflow for license/vuln scan

- .github/workflows/release.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Signed-off-by: Bob Callaway <bcallaway@google.com>
> fix deprecated set-output

- .github/workflows/release.yml
This is currently blocking the v0.0.7 release.
My understanding is that a breaking change happened to the TUF root meaning that older Sigstore libraries used to interact with TUF no longer work.
This job was previously pulling the provenance generator binary and then verifying it with Sigstore (this is the part that was breaking with the new TUF root). With `compile-generator`, the job will build the generator from source and avoid the Sigstore verification.
We should be able to get rid of this with a new release of `slsa-github-generator` is pushed.
Extended discussion at: https://github.com/slsa-framework/slsa-github-generator/issues/1163
> workflow: Workaround for SLSA generator failure

- sigstore/_verify/policy.py
- test/unit/verify/test_policy.py
This should make debugging `--cert-identity` failures a little easier.
xref https://github.com/sigstore/sigstore-python/pull/307#issuecomment-1322438494
> sigstore, test: add actual SANs to policy failure reason

- sigstore/_internal/oidc/oauth.py
The auth headers contain the OAuth client secret, which we shouldn't log (to minimize the chances of a user accidentally disclosing it while reporting bugs.)
> oidc/oauth: avoid logging the OAuth auth headers

- .github/workflows/release.yml
- README.md
- sigstore/__init__.py
- sigstore/_cli.py
This fixes the broken release test.
> sigstore: 0.8.1

- .github/workflows/release.yml
Fixes a `setup-python` actions warning.
> workflows/release: set python-version explicitly

- README.md
- sigstore/_cli.py
- sigstore/_utils.py
> _cli: Add `--certificate-chain` and support `--rekor-url` for verification

- sigstore/_cli.py
- sigstore/_sign.py
- sigstore/_utils.py
- sigstore/_verify/models.py
- sigstore/_verify/verifier.py
- test/unit/conftest.py
- test/unit/test_sign.py
- test/unit/test_utils.py
~~WIP; needs test updates and equivalent changes to verification.~~
Closes #158.
> sigstore: stream input into signing

- test/unit/internal/test_sct.py
This produces a lot of unnecessary testsuite noise, and might also be causing the stall in #334.
> test: avoid pre-computing large strings in parametrized tests

- .github/workflows/ci.yml
[A recent test run](https://github.com/sigstore/sigstore-python/actions/runs/3641503672/jobs/6147515676) seems to have caused a 500-level error with Rekor, but the full certificate that was uploaded in the test was truncated.
This PR ensures CI tests are run with full verbosity so long strings like certificates appear intact in the logs.
> Run tests in CI with full verbosity

- .github/workflows/ci.yml
- pyproject.toml
- sigstore/_cli.py
- sigstore/_internal/ctfe.py
- sigstore/_internal/rekor/client.py
- sigstore/_utils.py
- sigstore/_verify/verifier.py
- test/unit/test_store.py
This uses `importlib_resources` as a "polyfill" on older Python
versions, allowing us to use the new `resources.files()` APIs.
(These uses will be mostly removed with the TUF work in #25 anyways, but we might as well quash them for the time being.)
Closes #212.
> Eliminate deprecation warnings on 3.11

- .flake8
- .github/workflows/ci.yml
- CONTRIBUTING.md
- Makefile
- pyproject.toml
- sigstore/_utils.py
ruff is feature-complete (for our purposes) with flake8 and is an order of magnitude faster.
H/T @alex
> treewide: remove flake8, add ruff

- CHANGELOG.md
- README.md
- sigstore/_cli.py
This refactors `sigstore`'s logging behavior to the following:
1. `SIGSTORE_LOGLEVEL` now only affects the `sigstore.*` logger hierarchy
2. `-v` is added as an additive option;
1. `-v` corresponds to `SIGSTORE_LOGLEVEL=debug`
2. `-vv` corresponds to `<root logger>.setLevel("DEBUG")`
cc @jku 
Closes #371.
> _cli: refactor logging behavior

- sigstore/_internal/tuf.py
Old layout:
```
<cache-dir>/sigstore-python/
tuf-repo-1/
tuf-repo-2/
```
New layout:
```
<cache-dir>/sigstore/python/
tuf/
tuf-repo-1/
tuf-repo-2/
```
Closes #370.
cc @jku
> _internal/tuf: restructure TUF cache dir layout

- .github/workflows/ci.yml
- Makefile
- README.md
- sigstore/_cli.py
This adds `sigstore verify identity`, which is aliased (through some `argparse` hackery) back to `sigstore verify`.
This allows us to remain compatible with the existing CLI, while also giving us the flexibility we need to extend verification (e.g. `sigstore verify github`).
See #322.
> _cli: add `sigstore verify identity`

- .github/workflows/ci.yml
- .github/workflows/lint.yml
This allows us to remove the unnecessary schedule
and better isolates our CI concerns.
> workflows: move linting to a separate workflow

- Makefile
with the Makefile declaration
```
TESTS := 
```
```sh
$ make test TESTS="foo"
```
works as intended, but the definition overrides and pre-declaration of the `TESTS` variable,
```sh
$ TESTS="foo" make test
```
fix by only declaring if undefined using `?=`,
```
TESTS ?=
```
> FIX(jl): Makefile `TESTS` environment variable

- CHANGELOG.md
- pyproject.toml
> pyproject: bump pyOpenSSL >= 23.0.0

- .gitignore
- README.md
- pyproject.toml
- sigstore/_cli.py
- sigstore/sign.py
This adds initial support for Sigstore bundles during signing, in the form of the `--bundle` flag. When passed, `sigstore sign` will generate a single `{input}.sigstore` instead of separate `.crt`, `.sig`, and `.rekor` files.
I haven't included `sigstore verify` support in the initial changeset, in an effort to keep the diff small. But adding it shouldn't be difficult, and will provide a good dogfood/smoke test for round-tripping through the bundle format.
See #251.
> Initial Sigstore bundle support

- pyproject.toml
Changes our `tuf` constraint from `>= 2.0.0` to `~= 2.0.0`, since `tuf` is semantically versioned and we don't expect to be compatible with arbitrary major version changes.
cc @jku 
> pyproject: semver match for tuf dep

- Makefile
- pyproject.toml
See: https://github.com/pypa/pip-audit/pull/505
> pyproject.toml: Don't check for line-length with `ruff` since we're reformatting with `black`

- sigstore/_internal/sct.py
- sigstore/_internal/set.py
- sigstore/verify/verifier.py
- test/unit/test_sign.py
We generally use full-case format for abbreviations, so these were wrong.
> chore: rename some error types

- sigstore/_internal/tuf.py
The latest signing merge in https://github.com/sigstore/root-signing/commit/d35895290d0c54b6f01cb4c02da721a57b9d9c8c includes a target (`trusted_root.json`) that is missing the `custom` field.
This was previously failing with:
```
____________________________ test_signer_production ____________________________
@pytest.mark.online
def test_signer_production():
>       signer = Signer.production()
test/unit/test_sign.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
sigstore/sign.py:104: in production
rekor = RekorClient.production(updater)
cls        = <class 'sigstore.sign.Signer'>
updater    = <sigstore._internal.tuf.TrustUpdater object at 0x7fd25d604a90>
sigstore/_internal/rekor/client.py:280: in production
rekor_keys = updater.get_rekor_keys()
cls …
```
> Ignore targets missing the `custom` field

- sigstore/verify/models.py
I'll just give a dot point summary of what happened here:
- `mypy` released 1.1.1 which broke our lint.
- We committed 8a42a26943e144e053d21553dea4483dbc58f48a to fix this. We shouldn't have needed to do this because using the field name instead of the alias is not a bug, but we did this just to get things passing again.
- `pydantic` released 1.10.6 to fix their `mypy` plugin.
- Now the plugin is complaining that we're using the aliases and not the field name despite using `allow_population_by_field_name`.
- I'm making this PR to move back to using the field name.
There's still an underlying bug in `pydantic`'s `mypy` plugin as it should be fine to use the alias. This is described here: https://github.com/pydantic/pydantic/issues/5070
> verify: Stop using `pydantic` aliases in constructor to avoid `mypy` plugin bug

- sigstore/_errors.py
- sigstore/oidc.py
Bandit recently released v1.7.5, which includes [a new lint for `requests` usage without a timeout](https://bandit.readthedocs.io/en/1.7.5/plugins/b113_request_without_timeout.html). This changeset fixes our usage of `requests` in `oidc`.
> oidc: configure timeouts for `requests`

- .github/dependabot.yml
- .github/workflows/pin-requirements.yml
- .github/workflows/release.yml
This changeset resolves #115. We introduce a new workflow, `pin-requirements.yml`, which:
- Fetches the latest version of `sigstore-python` from PyPI;
- Updates the version in `requirements.in` from this version;
- Updates the pins in `requirements.txt` with `pip-compile`;
- Opens a pull request to `main` with these updates.
Here's a preview of what this pull request would look like: https://github.com/tnytown/sigstore-python/pull/2
Potential issues:
- Do we want to use a specific Python version for `pip-compile`? Would this affect the resultant `requirements.txt`?
- This workflow should run automatically on new PyPI releases, but I didn't test this end-to-end as I would have had to spin up some infrastructure. The trigger from `release.yml` may or may not work, we'll have to see when a …
> Pin requirements on releases with a workflow

- .github/workflows/pin-requirements.yml
This should prevent the bogus `file://` requirement.
> pin-requirements: fix wheel URL

- CHANGELOG.md
- sigstore/_internal/keyring.py
- sigstore/_internal/sct.py
See #547, #543.
In the SCT module, we now distinguish between the following kinds of verification errors:
- Invalid (potentially malicious) input signatures,
- Invalid key ID,
- Malformed input or API misuse.
> sct, keyring: specialize errors

- .github/workflows/pin-requirements.yml
- .github/workflows/requirements.yml
We now invoke the `requirements` workflow from `pin-requirements` to test install-ability. If any install fails, the requirements pinning PR is not opened.
Fixes #563.
> `pin-requirements` workflow self-test

- .github/workflows/ci.yml
- CHANGELOG.md
- CONTRIBUTING.md
- Makefile
- sigstore/oidc.py
- test/unit/conftest.py
- test/unit/test_sign.py
Introduces a new Makefile target `test-oidc`. This runs ambient OIDC tests with tokens from `sigstore get-identity-token`.
Partially fixes #570.
> Adapt ambient OIDC tests to support interactive flow for local testing

- CHANGELOG.md
- sigstore/_internal/keyring.py
- sigstore/_internal/tuf.py
- sigstore/_utils.py
- test/unit/internal/test_tuf.py
- test/unit/test_utils.py
This changeset modifies the TUF component to fetch keys from the `trusted_root.json` target, if available. `trusted_root.json` is a rollup of Sigstore component public keys. Using this target reduces the number of network roundtrips necessary to fetch keys individually.
Resolves #488.
> tuf: use bundled trusted root if available

- .github/actions/upload-coverage/action.yml
- Makefile
Use `pytest --cov-append` to not overwrite the `.coverage` artifact on each `make test` run. Aggregation avoids the problem of only the *last sequential test suite* ran being account for by getting last say on the `.coverage` contents.
Tracking against: https://github.com/sigstore/sigstore-python/actions/runs/4517097044#summary-12269011312
With aggregation: https://github.com/sigstore/sigstore-python/actions/runs/4547521585
Coverage increased by... a whole 1%
(note: thanks for the pointer, @0xalpharush!)
> Aggregate offline and online test coverage.

- sigstore/_internal/tuf.py
The TUF roots for both production and staging instances of sigstore are now addressable via a CDN endpoint; this change uses the CDN instead of calling GCS directly via its HTTP endpoint.
> swap over to using CDN to fetch TUF roots

- .github/workflows/conformance.yml
This should no longer be necessary.
> conformance: remove old id-token permission

- CHANGELOG.md
- sigstore/_cli.py
- sigstore/oidc.py
This API accidentally gained a parameter in a point release, which is both a semver breakage and strictly unnecessary (since the parameter is an invariant).
> sigstore: fix `detect_credential` signature

- CHANGELOG.md
- README.md
- sigstore/_cli.py
- test/integration/sigstore-python-conformance
> cli: Remove default subcommand hack

- CHANGELOG.md
- sigstore/verify/verifier.py
Our previous check was incorrect: it would fail verification on an otherwise valid inclusion proof if the integrated time happened to be at the last moment of `not_valid_after`.
See: https://github.com/sigstore/protobuf-specs/pull/78
> verify: fix timerange inclusion check

- sigstore/sign.py
This is a follow-on to #662: I missed a callsite while deconflicting.
> sign: switch another keysite to P-256

- CHANGELOG.md
- README.md
- sigstore/_cli.py
- sigstore/_utils.py
- sigstore/oidc.py
- test/unit/internal/oidc/test_issuer.py
Adresses comment https://github.com/sigstore/sigstore-python/issues/665#issuecomment-1574033667
> feat: Add `--oauth-force-oob` CLI option

- CHANGELOG.md
- sigstore/_internal/sct.py
- sigstore/_utils.py
- test/unit/test_utils.py
Previously, TBSCertificate signed with the same CA than the final certificate was failing if no `ExtendedKeyUsage` were present
Fix a case where signing an artifact against a private sigstore instance was failing if no `ExtendedKeyUsage` was present in the Sigining CA
NONE
Resolves: sigstore/sigstore-python#658
> Handle the case of missing EKU in _is_preissuer

- CHANGELOG.md
- sigstore/_internal/rekor/client.py
I don't think we need to pass a parsed JSON object up to the caller in the context of `RekorClientError`
@woodruffw thoughts?
> don't parse error messages as json

- sigstore/sign.py
A really small fix to include the `SigningContext` import in the example given in `sign.py`.
NONE
> Fix missing SigningContext import in sign example

- sigstore/sign.py
This commit fixes the issue described in #700 where the certificate `not_valid_after` datetime is not tz-aware, making the call to `timestamp()` to assume local time, triggering the `ExpiredCertificate` exception all the time.
Resolves: #700 
- Fixes a issue in the certificate expiration timestamp that caused exception during signing process.
> Add timezone (utc) info into the cert not_valid_after field

- sigstore/sign.py
Minor change to fix the documentation about the sign API, the current one is outdated.
- Minor change in documentation to reflect sign API changes.
> Fixing documentation message about the sign API

- sigstore/__init__.py
Puts another release candidate out there; this will help us fix the conformance suite's self-tests and hopefully expose us to some more user testing before a final 2.0.0.
> sigstore: 2.0.0rc2

- CHANGELOG.md
- sigstore/verify/models.py
- test/unit/verify/test_models.py
Part of https://github.com/sigstore/sigstore-python/issues/718, adds the API to convert `VerificationMaterials` that have a Rekor entry loaded into a `Bundle`.
Will add a release note.
I don't think this needs a docs update?
> Add VerificationMaterials.to_bundle()

- .github/dependabot.yml
I suspect that dependabot is not picking up on the `/install/.python-version` file because it's being run from the root of the repository. A separate config should fix that.
> Try separate config for /install directory

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/requirements.yml
- CONTRIBUTING.md
- README.md
- pyproject.toml
Python 3.7 is currently EOL: https://devguide.python.org/versions/
Current versions of `sigstore-python` (<=1.1.2) will continue to be usable from Python 3.7.
> Drop support for Python 3.7

- README.md
This makes the badge link to the new Scorecard viewer: https://securityscorecards.dev/viewer/?uri=github.com/sigstore/sigstore-python
> Update securityscorecards.dev URL

- .github/workflows/pin-requirements.yml
> pin-requirements: explicitly fetch tags

- .github/pull_request_template.md
- CHANGELOG.md
- sigstore/_cli.py
- sigstore/sign.py
This enables signing applications to use the bundle format and seems in line with the other similar decisions:
* The bundle is already part of the CLI interface
* verify already contains similar public API (VerificationMaterials.from_bundle() is public)
Closes #763
* API addition: `sign.SigningResult.to_bundle()` allows signing applications to serialize to the bundle format that is already usable in verification with `verify.VerificationMaterials.from_bundle()`
* Method already has a docstring
* A complete example of _sign -> bundle serialization -> bundle deserialization -> verify_ could be useful but I did not add one here
> sign: Make SigningResult._to_bundle() public

- CHANGELOG.md
- README.md
- sigstore/__init__.py
- sigstore/transparency.py
~~Draft until we're ready to merge this.~~
> Prep 2.0.0

- pyproject.toml
- sigstore/_internal/rekor/client.py
- sigstore/sign.py
- sigstore/verify/models.py
- test/unit/verify/test_models.py
> rekor: use sigstore_rekor_types for models

- sigstore/_internal/fulcio/client.py
- sigstore/_internal/rekor/client.py
Raised in https://github.com/sigstore/sigstore-python/actions/runs/6535290203/job/17744388682?pr=792:
```
sigstore/_internal/fulcio/client.py:236: error: Item "None" of "Optional[Response]" has no attribute "text"  [union-attr]
sigstore/_internal/rekor/client.py:188: error: Item "None" of "Optional[Response]" has no attribute "status_code"  [union-attr]
```
> Fix some mypy linting failures

- CHANGELOG.md
- sigstore/_cli.py
Fixes #795
Fix opening the PEM file argument of the `--certificate-chain` option in `sigstore verify <identity, github>` as `bytes` instead of `str`.
None
> Read Fulcio certificate chain as bytes in verify command

- CONTRIBUTING.md
- Makefile
- pyproject.toml
- sigstore/verify/models.py
- sigstore/verify/verifier.py
- test/unit/internal/test_sct.py
This speeds up our `lint` and `reformat` targets a bit, and drops a dev dependency (since we're already using ruff).
> treewide: switch to `ruff format`

- pyproject.toml
- sigstore/_cli.py
This adds `rich` as a dependency, using its `RichHandler` logging handler to make our logging much prettier by default (when invoked from the CLI).
I'm not 100% sure this is worth it; opening for discussion/consideration 🙂 
Pros:
* Makes our logging much easier to read/visually distinguish. This is particularly helpful for cases where we use `logger.warning(...)` to emit deprecation notices, which otherwise could be missed in the monochromatic/unformatted output.
Cons:
* Heavyweight?
Demo:
[![asciicast](https://asciinema.org/a/SLESuadskrCIMJMnZvLFOaI0N.svg)](https://asciinema.org/a/SLESuadskrCIMJMnZvLFOaI0N)
> _cli: use rich's logging handler

- pyproject.toml
I've yanked 0.0.12 so the error is no longer manifest, but this will prevent us (meaning me) from accidentally breaking everything when I make incompatible changes.
Once this is in, we should cut a point release to propagate it. From there, we can cut a new release of `sigstore-rekor-types` and conservatively upgrade to it.
xref https://github.com/sigstore/gh-action-sigstore-python/issues/94
> pyproject: sigstore-rekor-types==0.0.11

- .github/actions/upload-coverage/action.yml
- .github/workflows/ci.yml
- .github/workflows/conformance.yml
- .github/workflows/lint.yml
- .github/workflows/pin-requirements.yml
- .github/workflows/release.yml
- .github/workflows/requirements.yml
- .github/workflows/scorecards-analysis.yml
- .github/workflows/staging-tests.yml
Closes #837
While looking at the workflow files I noticed that some actions used versions and others used hashes. I also observed that some actions (like `actions/checkout` in several places) had incorrect version comments (claiming that hash `X` was `v3.3.0`, which was incorrect).
If the version comment is incorrect, Dependabot fails to update it in its PRs. This is evident in a Dependabot PR that is currently open: #836 [fails to update the version comment in `scorecards-analysis.yml`](https://github.com/sigstore/sigstore-python/pull/836/files#diff-43563750699358bcd52e44e9a2700c2e4e9b27512b60dd60c204c4007d3764a9L47-R47).
I *think* that I've followed the contributing guidelines, including opening an issue, linking this PR to that issue, and signing-off the git commit, but please let me …
> Standardize hashes and version comments in workflows

- .github/dependabot.yml
Make the internal action in .github/actions/upload-coverage managed by dependabot. 
This (and the resulting dependabot PR) should unblock #835
> dependabot: Manage the internal action as well

- .github/actions/upload-coverage/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/scorecards-analysis.yml
Refactor upload-coverage to enable upgrading the upload-artifact and download-artifact actions (as the new upload-artifact does not allow uploading with the same name several times).
* Use unique artifact names, then download all artifacts before combining them for coverage
* Upgrade the actions
N/A
> Refactor upload-coverage action

- .github/dependabot.yml
This will cut our automated PR volume down slightly: GHA updates from Dependabot will now be batched into one big PR, rather than one PR per updated action.
> dependabot: group GHA updates

- sigstore/_cli.py
- sigstore/_internal/rekor/client.py
- sigstore/_internal/trustroot.py
- sigstore/_internal/tuf.py
- sigstore/sign.py
- sigstore/verify/verifier.py
- test/unit/conftest.py
- test/unit/internal/test_trust_root.py
- test/unit/verify/test_models.py
The purpose of this is to later enable both "--trust-root <FILE>" and some sort of "--offline" functionality.
* Trust root can now be initialized from tuf, offline tuf or from a file
* `_internal.tuf` module is now used only from the new `_internal.trustroot` module
* all "trust root parsing" was moved from `_internal.tuf` to `_internal.trustroot`
* Tests are modified to use the trustroot module now but they still (also) test the internal TUF implementation details
* The new functionality (offline & from_file) is tested but is not exposed to UI
The main functional change as I see it is in TrustedRoot/TrustUpdater initialization. There are three possible scenarios (once this is exposed through UI):
* A trust root is provided as a file: TrustedRoot never instantiates a TrustUpdater
* …
> Separate TUF and trusted root management code

- CHANGELOG.md
- pyproject.toml
- sigstore/_cli.py
- sigstore/_utils.py
- sigstore/sign.py
- sigstore/verify/verifier.py
- test/unit/conftest.py
- test/unit/test_sign.py
This removes the `SigningResult` model, and replaces it with `Bundle` in APIs where a `SigningResult` was previously returned.
Closes #854.
Unblocks #860.
cc @laurentsimon for visibility 🙂
> API: remove SigningResult

- CHANGELOG.md
- sigstore/_cli.py
- sigstore/_utils.py
- sigstore/hashes.py
- sigstore/sign.py
- sigstore/verify/models.py
- sigstore/verify/verifier.py
- test/unit/conftest.py
- test/unit/test_sign.py
closes https://github.com/sigstore/sigstore-python/issues/666
Let me know if you'd like me to add a dedicated unit test for this new option.
Context: I'm working on adding a new hash type to rekor to support hashing directories. I will need to follow up to add support for it in https://github.com/trailofbits/sigstore-rekor-types. 
Test example with pre-computed sha256:
```python
from sigstore import hashes as sigstore_hashes
from sigstore_protobuf_specs.dev.sigstore.common.v1 import HashAlgorithm
with file.open(mode="rb", buffering=0) as io:
digest = hashlib.sha256(io.read())
hashed = sigstore_hashes.Hashed(digest=digest, algorithm=HashAlgorithm.SHA2_256)
result = signer.sign(hashed)
```
This PR enables passing a pre-hashed value instead of the content to be hashed.
> feat: Enable signing with pre-computed hash

- sigstore/verify/policy.py
After this we have no uses of typing-extensions. It was not actually listed as a (direct) dependency at all.
> verify: Remove a workaround for pre-3.8 Python

- pyproject.toml
- sigstore/sign.py
- sigstore/verify/verifier.py
`Certificate.not_valid_before` and `Certificate.not_valid_after` have been deprecated in cryptography 42.
* Require cryptography >= 42 (because the replacement fields are only available there)
* Use the new fields in `verify` and `sign`
This seems straight forward to me but review from someone certificate savvy wouldn't hurt.  The only interesting bit to me seems to be that we now give X509Store  a datetime that is explicitly UTC -- but I don't see that changing anything.
Fixes #878
> Fix cryptography deprecations

- sigstore/_internal/rekor/checkpoint.py
This data was always optional, and we weren't using it anyways. 
Fixes #889.
> rekor/checkpoint: handle missing ancillary data

- .github/workflows/ci.yml
- CHANGELOG.md
This cherry-picks the release prep work from `series/2.1.x` back onto `main`.
> Merge CLs from 2.1.x series

- pyproject.toml
- sigstore/_internal/tuf.py
Closes #867 
Is replaces the lib to generate paths `appdirs` with `platformdirs`. This lib is used only in the tuf file.
As described on the issue #867 the `appdirs` has been deprecated.
Removed appdirs from dependencies.
Added platformdirs to dependencies.
Updated tuf.py code to use platformdirs instead of appdirs for path generating.
> Replace appdirs with platformdirs on tuf

- CHANGELOG.md
- pyproject.toml
- sigstore/_utils.py
- sigstore/sign.py
- sigstore/verify/models.py
- test/unit/test_utils.py
Bumps `sigstore-protobuf-specs`, giving us access to the latest Bundle version.
> sigstore: v3 bundles

- pyproject.toml
ruff now prefers these options under tool.ruff.lint
> pyproject: Update lint options section

- CHANGELOG.md
- sigstore/_cli.py
- sigstore/_utils.py
- sigstore/sign.py
- sigstore/verify/verifier.py
- test/unit/test_sign.py
- test/unit/test_utils.py
- test/unit/verify/test_models.py
- test/unit/verify/test_verifier.py
Counterpart to #904: `Signer.sign(...)` takes `bytes` instead of an effectful IO type.
> sigstore/sign: sign API takes bytes, not I/O

- CHANGELOG.md
- pyproject.toml
- sigstore/__init__.py
This will help resolve the mess I've caused in https://github.com/sigstore/sigstore-conformance/pull/136.
> pyproject: bump protobuf specs

- sigstore/_cli.py
- sigstore/_internal/fulcio/client.py
- sigstore/_internal/oidc/oauth.py
- sigstore/_internal/rekor/client.py
- sigstore/_internal/sct.py
- sigstore/_internal/tuf.py
This is for hygiene/consistency: `logger` is never intended to be a public API in any of our modules.
No functional changes.
> sigstore: rename more logger instances

- CHANGELOG.md
- pyproject.toml
- sigstore/__init__.py
This is for **series/2.1.x**
Only change is pinning securesystemslib so future major or minor
releases will not be used (current release is 0.31.0)
We can still discuss if this makes sense or is necessary.
Fixes #960
> Prepare 2.1.4 release

- .github/workflows/release.yml
- CHANGELOG.md
Forward port from series/2.1.x:
* Changelog updates
* Fix for release workflow: don't use hash for slsa generator action
> Forward ports from series/2.1.x

- CHANGELOG.md
- sigstore/_cli.py
- sigstore/sign.py
- test/unit/test_sign.py
Per https://github.com/sigstore/sigstore-python/issues/628: this turns `sign(...)` into `sign_artifact(...)` and `sign_intoto(...)` respectively. In doing so, we're also able to simplify and deduplicate the internals of the `Signer` class a bit.
> sigstore, test: break apart DSSE/artifact sign APIs

- pyproject.toml
- sigstore/sign.py
Addresses https://github.com/sigstore/sigstore-python/pull/957.
See <https://github.com/pydantic/pydantic/discussions/7418#discussioncomment-9024927> and <https://github.com/koxudaxi/datamodel-code-generator/issues/1903> for additional context about the `type: ignore`.
> bump sigstore-rekor-types, add NOTE

- .github/workflows/ci.yml
- test/unit/conftest.py
- test/unit/test_sign.py
- test/unit/verify/test_verifier.py
* Add ability to disable staging tests in unit tests
* disable staging temporarily because it's currently not reliable
Possibly open issues:
* I have not taken a hard look at whether our coverage is still good enough without the staging tests or not
* `make test` default is not affected: developers need to `TEST_ARGS=--skip-staging  make test`
* If this is merged, need to file a reminder to remove `--skip-staging` at some point
Fixes #988
> Disable staging in tests

- sigstore/models.py
- test/unit/test_models.py
This moves the logic that converts between `rekor_v1.TransparencyLogEntry` and `sigstore.models.LogEntry` to their own separate functions:
```python
@classmethod
def _from_dict_rekor(cls, dict_: dict[str, Any]) -> LogEntry:
...
def _to_dict_rekor(self, is_message_signature: bool) -> dict[str, Any]:
...
```
The motivation for having these available is [PEP 740](https://peps.python.org/pep-0740/), which defines an attestation format for PyPI artifacts. This PEP doesn't define a specific transparency log entry format, rather it leaves the choice to the implementation. In practice, it makes sense to use the exact same structure as a `rekor_v1.TransparencyLogEntry` for these entries. Using a different structure is not necessary and would introduce another format conversion to keep track of. …
> sigstore: extract LogEntry conversions to their own functions

- .github/workflows/ci.yml
- test/unit/conftest.py
- test/unit/test_sign.py
~~WIP, trying other routes as well.~~
This ensures that tests using `env` to load the staging instance are also skipped by `--skip-staging`.
> test_sign: disable more staging tests

- CHANGELOG.md
- README.md
- sigstore/_cli.py
This completes our migration to both emitting and verifying `{foo}.sigstore.json` by default. 3.0 will include `sigstore verify` falling back to `{foo}.sigstore` if `.sigstore.json` isn't present, but this fallback can be removed in 4.0.
Closes #814.
CC @loosebazooka for viz, since I know you've looked at similar things recently 🙂
> _cli: emit .sigstore.json by default

- pyproject.toml
- sigstore/_internal/trustroot.py
- sigstore/dsse.py
- sigstore/models.py
Bumps us to `~= 0.3.2`. This patch release enables type hinting, allowing us to refine the types a bit here.
> bump sigstore-protobuf-specs

- sigstore/_internal/__init__.py
- sigstore/_internal/fulcio/client.py
- sigstore/_internal/rekor/client.py
- sigstore/oidc.py
This sets the UA in the Fulcio, Rekor, and OIDC clients. I haven't touched the TUF client since I wasn't sure how to access the underlying `requests.Session` there 🙂 
See #985.
> sigstore: uniform user-agent with sigstore version

- CHANGELOG.md
- sigstore/oidc.py
- test/unit/test_oidc.py
See #970 and #567: this renames `expected_certificate_subject` to `federated_issuer` in an attempt to better clarify what this property is actually returning.
> oidc: rename expected_certificate_subject -> federated_issuer

- pyproject.toml
- sigstore/_internal/tuf.py
- test/unit/conftest.py
The ngclient API that we use is fully backwards-compatible but I want to do two small changes so am bumping the required version:
* Don't poke into fetcher internals: the timeout is now the 30 seconds we wanted
* set user-agent through UpdaterConfig: this will end up as "sigstore-python/3.0.0rc2 tuf/5.0.0 python-requests/2.31.0" (a bit verbose perhaps but all of that is useful)
> Upgrade tuf dependency

- CHANGELOG.md
- README.md
- sigstore/_cli.py
- sigstore/dsse.py
- sigstore/hashes.py
- sigstore/verify/policy.py
This allows for a _very_ limited form of DSSE verification via the `sigstore` CLI. In particular, it allows a DSSE-containing bundle to be verified, but only if:
* The DSSE payload is JSON;
* The JSON is an in-toto statement;
* The in-toto statement has at least one subject matching the input file's digest.
This limited form is compatible with what GitHub Artifact Attestations is doing and, in particular, is compatible with how `gh attestation verify` behaves.
~~WIP while I clean things up a little.~~
Closes #999.
Closes https://github.com/sigstore/sigstore-python/issues/780.
> cli: allow DSSE verification

- README.md
Small doc improvements, following #1015.
> README: improve `verify github` examples

- .github/workflows/release.yml
This is purely a defense in depth maneuver: an attacker could only poison our cache here by running arbitrary code on `main`. But we probably shouldn't be caching anyways, since it makes the release process/state more opaque 🙂 
Context: https://adnanthekhan.com/2024/05/06/the-monsters-in-your-build-cache-github-actions-cache-poisoning/
> release: remove pip cache usage

- sigstore/_internal/rekor/checkpoint.py
- sigstore/_internal/sct.py
- sigstore/_utils.py
Just some small type-checking related cleanup: removes two almost completely unused `NewType`s and puts an import into a `TYPE_CHECKING` block.
> sigstore: type cleanup

- sigstore/models.py
Adds an explicit annotation for a type produced through `TypeAdapter`.
As best I can tell, this is the proximate behavior change in pydantic: https://github.com/pydantic/pydantic/pull/9570
(Unblocks our broken CI in the rest of the outstanding PRs.)
> models: add type annotation

- CHANGELOG.md
- sigstore/dsse.py
This makes us more consistent with the protobuf-specs specified behavior, which stipulates that DSSEs should only contain one signature in the context of Sigstore bundles.
See also: https://github.com/sigstore/sigstore-go/issues/225f
> sigstore/dsse: reject DSSEs with >1 sig

- CHANGELOG.md
- sigstore/dsse.py
- test/unit/test_sign.py
- test/unit/verify/test_verifier.py
Adds the public `StatementBuilder` API, created by making `_StatementBuilder` public. Also adds an alternative construction route for `Statement`, allowing it to be directly constructed from an internal (still private) `_Statement`, avoiding an unnecessary serde round-trip.
Note: This makes `StatementBuilder` public, but explicitly doesn't commit it to SemVer just yet; I don't expect it to change very much, but in the event it does I don't want us locked into design decisions for the entire 3.x lifetime 🙂 
Closes #1076.
> API: make _StatementBuilder public

- CHANGELOG.md
- sigstore/dsse.py
- test/unit/test_sign.py
- test/unit/verify/test_verifier.py
Follows #1077.
These are needed to make the StatementBuilder public API functional/useful.
I'll do a minor release once this lands 🙂 
CC @mihaimaruseac
> dsse: make constituent types public

- CHANGELOG.md
- sigstore/__init__.py
Gets `sigstore plumbing` et al. out the door so @sethmlarson can use then 🙂
> prep 3.2.0

- pyproject.toml
Before, `setuptools` was included in the `lint` dependencies due to a bug in `interrogate`. Since that bug was [fixed](https://github.com/econchick/interrogate/issues/164#issuecomment-2041231552), we remove `setuptools` and add a constraint to the `interrogate` version to ensure we use a version with the fix.
cc @woodruffw
> Add minimum version to interrogate dependency

- CHANGELOG.md
- sigstore/_cli.py
Part of https://github.com/sigstore/sigstore-python/issues/1111. This changes the `sigstore verify` CLI command so that when verifying a bundle containing a DSSE envelope, if verification succeeds the inner in-toto statement is printed to the user.
```sh
$ sigstore verify identity README.md --cert-identity me@example.com --cert-oidc-issuer https://issuer.example.com
OK: README.md
{"_type":"https://in-toto.io/Statement/v1","subject":[{"name":"README.md","digest":{"sha256":"033be49064ed2a5f50bf81950f38741a8c550bc8076447452152c7b9d28728bc"}}],"predicateType":"slsaprovenance0_2","predicate":{"builder":{"id":"https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v2.0.0"},"build_type":"https://github.com/slsa-framework/slsa-github-generat …
```
> Print in-toto statement when verifying DSSE

- .github/workflows/ci.yml
- .github/workflows/requirements.yml
- pyproject.toml
The final Python 3.13 release candidate is out now! :rocket:
The Release Manager has issued a [call to action](https://discuss.python.org/t/python-3-13-0rc2-3-12-6-3-11-10-3-10-15-3-9-20-and-3-8-20-are-now-available/63161?u=hugovk]):
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.13 compatibilities during this phase, and where necessary publish Python 3.13 wheels on PyPI to be ready for the final release of 3.13.0. Any binary wheels built against Python 3.13.0rc2 will work with future versions of Python 3.13. As always, report any issues to [the Python bug tracker](https://github.com/python/cpython/issues).
Add support adding 3.13 to CI and Trove classifiers.
"Add support for Python 3.13." but I don't see changelog entries for past …
> Add support for Python 3.13

- sigstore/_cli.py
- sigstore/dsse/_predicate.py
Follow up to https://github.com/sigstore/sigstore-python/pull/1115#discussion_r1752718866 and https://github.com/sigstore/sigstore-python/pull/1115#discussion_r1759058534.
This PR:
- Changes `sigstore attest` to sign over the predicate file's contents, rather than our Pydantic model JSON dump. See the comments in the code for the rationale.
- Changes the implementation to use an `enum.Enum` for the predicate types
- Forbids unexpected fields in predicate JSON during model validation
cc @woodruffw
> Attestation CLI command improvements

- CHANGELOG.md
- README.md
- sigstore/_cli.py
- sigstore/hashes.py
- test/unit/test_hashes.py
This PR changes the `sigstore verify` CLI command so that it accepts digests as inputs (in addition to files).
Concretely:
```shell
sigstore verify identity ..... path/to/artifact.zip  # can only verify an artifact
sigstore verify identity ..... path/to/artifact.zip  # can verify an artifact
sigstore verify identity ... --bundle b.sigstore.json sha256:aaabbbb.....  # can also verify an artifact's digest
```
This is useful in scenarios where the user doesn't want/need to download the artifact, but has access to its digest.
Related to https://github.com/sigstore/sigstore-conformance/issues/157
* CLI: The `sigstore verify` command now supports verifying digests. This means
that the user can now pass a digest like `sha256:aaaa....` instead of the
path to an artifact, and `sigstore-python` …
> Add support for verifying digests to CLI verify commands

- CHANGELOG.md
- sigstore/__init__.py
Release 3.3.0
cc @woodruffw 
Changelog:
* CLI: The `sigstore verify` command now outputs the inner in-toto statement
when verifying DSSE envelopes. If verification is successful, the output
will be the inner in-toto statement. This allows the user to see the
statement's predicate, which `sigstore-python` does not verify and should be
verified by the user.
* CLI: The `sigstore attest` subcommand has been added. This command is
similar to `cosign attest` in that it signs over an artifact and a
predicate using a DSSE envelope. This commands requires the user to pass
a path to the file containing the predicate, and the predicate type.
Currently only the SLSA Provenance v0.2 and v1.0 types are supported.
* CLI: The `sigstore verify` command now supports verifying digests. This means
that the …
> prep 3.3.0

- test/conftest.py
- test/integration/cli/conftest.py
- test/integration/cli/test_attest.py
- test/integration/cli/test_plumbing.py
- test/integration/cli/test_sign.py
- test/unit/conftest.py
Follow up to https://github.com/sigstore/sigstore-python/pull/1124#discussion_r1765692720. Move the common fixtures to `test/conftest.py`, and use `test/unit/conftest.py` and `test/integration/cli/conftest.py` for the unit/integration-specific fixtures.
cc @woodruffw
> Deduplicate test fixtures

- CHANGELOG.md
- README.md
- sigstore/_cli.py
- sigstore/_internal/tuf.py
- sigstore/verify/verifier.py
- test/unit/verify/test_verifier.py
With this change, `--offline` also disables TUF
repository updates and not just online log lookups.
Needs unit and integration tests; working on that now.
Closes #483. Closes #376.
CC @sethmlarson
> cli: --offline means fully offline

- .github/workflows/release.yml
This enables attestation generation while uploading to PyPI. Future versions of the `gh-action-pypi-publish` action will enable this by default, but we want to get in on the ground floor.
It also disables uploading of the "smoketest" artifacts to the GitHub-side release, since these don't correspond 1-1 with the PyPI attestations (they're composed only of hashes of the file, and don't use a DSSE payload). This will hopefully eliminate some confusion + guide users towards the PyPI hosted ones as canonical.
> workflows/release: enable PEP 740 attestations

- CHANGELOG.md
- sigstore/_cli.py
This fixes a small edge case where a user supplies `sha256:hash.jsonl` or similar (such as produced by default by `gh attestation`) and the `sigstore verify` subcommands interpret it as an (invalid) hash rather than a file input.
The new behavior is to always interpret the input as a path if a file at that path is extant, and to otherwise interpret it as a hash.
CC @facutuesca
> _cli: files always take precedence over digests

- pyproject.toml
No fuctional change; just fixes a piece of metadata that incorrectly marked us as still beta-quality.
> pyproject: fix status classifier

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- pyproject.toml
- test/integration/cli/test_sign.py
> bump minimum Python to 3.9

- .github/workflows/requirements.yml
This was breaking the pin-requirements workflow.
> workflows/requirements: remove a lingering 3.8 reference

- CHANGELOG.md
- sigstore/_cli.py
This adds a new plumbing-level command: `update-trust-root`. When run, `sigstore plumbing update-trust-root` will perform a TUF update for the appropriate production or staging trust root, depending on whether the top-level `--staging` flag is used.
Closes #1172.
CC @mgorny if you can, it'd be great to have you trial this locally to confirm it meets your needs! In particular it'd be useful to know if you'd prefer it to be "louder" in terms of outputs, i.e. print something on `stdout`/`stderr`.
> _cli: add `plumbing update-trust-root`

- CHANGELOG.md
- sigstore/__init__.py
Preps 3.5.0. Also adds a missing changelog entry for #1179.
CC @sethmlarson
> Prep 3.5.0

- CHANGELOG.md
- sigstore/_cli.py
This fixes the check added in https://github.com/sigstore/sigstore-python/pull/1179 by ensuring that we don't bypass the legacy bundle discovery behavior by accident when trying to suppress the warning.
I'll do a bugfix release after this.
> _cli: fix warning check

- CHANGELOG.md
- sigstore/_cli.py
- test/assets/integration/bundle_v3.txt
- test/assets/integration/bundle_v3.txt.sigstore
- test/integration/cli/test_verify.py
This PR fixes a check in the CLI command `sigstore verify` where we should have printed a warning while verifying a legacy bundle (`*.sigstore`) if no bare materials (`*.crt` and `*.sig`) are provided.
The warning was never printed, due to an error in the check that made it always return `False`.
This PR also adds a regression test for the bug fixed in https://github.com/sigstore/sigstore-python/pull/1192, checking that the CLI correctly verifies a legacy bundle and that it logs the expected warning.
This closes https://github.com/sigstore/sigstore-python/issues/1194.
cc @woodruffw
> Fix warning for CLI verification of legacy bundles

- pyproject.toml
Bumps `sigstore-rekor-types` to `0.0.18`, incorporating minor (non-behavior in this case) codegen changes from `rekor` `v1.3.7`.
> pyproject: bump sigstore-rekor-types

- CHANGELOG.md
> CHANGELOG: record #1216

- sigstore/_internal/fulcio/client.py
- test/unit/internal/fulcio/test_client.py
Per #1231 -- this removes our assumption that `SignedCertificateTimestamp` is an ABC. 
This doesn't perform the cryptography bump yet, but it _does_ unblock an upstream regression test: https://github.com/pyca/cryptography/pull/12054
> fulcio: remove ABC registration

- CHANGELOG.md
- pyproject.toml
This bumps rfc3161-client, which will both remove a spurious `maturin` runtime dep *and* make us compatible with older versions of `cryptography`, preventing resolution hell.
> bump rfc3161-client

- .github/workflows/release.yml
No longer necessary since `pypa/gh-action-pypi-publish` v1.11.0.
(h/t @haydentherapper)
> Remove vestigial `attestations: true`

- CHANGELOG.md
- sigstore/__init__.py
Just a small bump to get the cryptography version range fix out the door.
Closes #1250.
> sigstore: prep 3.6.1

- sigstore/_internal/fulcio/client.py
- sigstore/_internal/sct.py
- sigstore/sign.py
- sigstore/verify/verifier.py
Simplify SCT management in fulcio client and the sites that need to call verify_sct()
* SCTs are only needed inside `verify_sct()`: Make them an implementation detail and stop exposing them in FulcioCertificateSigningResponse (which is internal, so this is not an API change)
* The only functional change is that `FulcioCertificateSigningResponse` may now exist without a valid SCT: In practice Signer works just like before since we call `verify_sct()`  on the cert immediately after getting the response
* Also remove an unused exception
There are two commits but I recommend reviewing the PR as a whole.
Fixes #1258.
N/A: No public API changes or CLI changes are expected.
> Minor refactoring of Fulcio SCT handling

- .github/workflows/ci.yml
~~WIP.~~
This "fixes" the CI by effectively undoing the namespace default changes that Ubuntu made between 22.04 and 24.04. Doing this should have no security impact in practice, since we're already running with full root access on these runners.
The other option here would be to remove `unshare` entirely, and continue to test the offline tests without actually enforcing their offline-ness. However, I think it's good to keep this around as a backstop, at least for as long as we can 🙂
> ci: fix offline tests on ubuntu-latest

- .github/workflows/check-embedded-root.yml
- Makefile
* Add `make update-embedded-root` rule
* Add workflow that files an issue if root is not up-to-date
I'm not sure if the workflow is really needed but I decided to include it. I think automatically making a PR might be a bad idea (since there are test suite tests for this we'd be trusting CI 100% and that doesn't sound right in this case).
--- 
Makefile rule uses the "plumbing" command to ensure the newest root has been downloaded and verified. Then it copies the newest TUF root and the trusted_root.json into the sources. The benefit here is that one does not need to manually find the cache directories when an update should be done.
Makefile rule hard codes XDG_DATA_HOME and XDG_CACHE_HOME for simplicity.
The workflow adds a new CI-dependency (github-script) but I believe the currently …
> Makefile: Add update-embedded-root rule

- pyproject.toml
Instead of explicitly selecting `E` and `F` rules, use ruff default rules, which include `F` rules and `E` rules compatible with formatters:
https://docs.astral.sh/ruff/settings/#lint_extend-select
According to the Scientific Python Library Development Guide, `W` rules are not needed when using a formatter:
https://learn.scientific-python.org/development/guides/style/#ruff
Also enforce `UP` ruff rules.
Requires #1319.
I might be mistaken, but probably not needed.
N/A
> ruff settings: select → extend-select

- pyproject.toml
- sigstore/_internal/tuf.py
- test/unit/conftest.py
- test/unit/internal/test_trust.py
This is not really urgent but I wanted to open this before the dependabot update comes in.
I think the potentially annoying part here is the certificate source: it's not ideal that some parts of sigstore-python will now be using certifi certs and the tuf client will be using system certs... but the choice made here is in line with #1040 
The big changes in tuf 6.0 are dependencies:
* no longer uses requests but directly urllib3
* no longer uses certifi
The included code change in this PR is not strictly necessary but is potentially a little more secure (tuf client no longer trusts the metadata cache but always initializes the Updater from the embedded root).
The test changes are related to
* assumptions we make on the tuf metadata cache content
* our tests mocking a feature that was …
> Upgrade to tuf 6.0

- CHANGELOG.md
- sigstore/_internal/trust.py
Rekor keyring can (and in future will) have multiple keys: logs not only get sharded but once rekor-tiles is integrated in the public good instance, there will be two writable logs for a while.
As far as I can tell all calling code is already capable of handling the keyring.
Fixes #1349
> _internal/trust: Fix bug in rekor key lookup

- CHANGELOG.md
- sigstore/__init__.py
Minor bump, the only noteworthy change is the tuf dependency bump.
---
* I'd like to do this since ephemeral CDN failures in various sigstore infra tests end up showing a lot more python-tuf tracebacks than I'd like
* the urllib3 changes should help there because of the default retry policy
* that said, there's no real urgency: happy to wait for some other changes too
> prep 3.6.2

- CHANGELOG.md
- pyproject.toml
- sigstore/_cli.py
- sigstore/_internal/trust.py
- sigstore/hashes.py
- sigstore/models.py
- sigstore/sign.py
- sigstore/verify/verifier.py
- test/assets/signing_config/signingconfig.v2.json
- test/assets/trust_config/config.badtype.json
- test/assets/trust_config/config.v1.json
- test/unit/internal/test_trust.py
This is built on top of #1276: I'm fine with merging that first or closing that one and merging all the proto changes at once in this PR.
This PR upgrades us to the most recent protobuf-specs. Changes include (on top of 1276):
* A new signingconfig version is supported, and a `SigningConfig` class has been added to handle parsing the data in it
* I'm removing support for SigningConfig 0.1 since that was not actually usable: I don't think anyone will mind (staging currently has 0.1 but we do not use it and 0.2 should be available in staging by next week)
I'd like to handle followups in other PRS, mainly I'm thinking of:
* rekorclient is still a bit of a mess
* the signingconfig service selectors are not fully supported yet
* oidc provider is still hard coded when running CLI
* …
> More proto updates

- CHANGELOG.md
- sigstore/_internal/timestamp.py
- test/unit/internal/test_timestamping.py
[Client support for Rekor V2: sigstore-python](https://github.com/sigstore/rekor-tiles/issues/289)
Resolves https://github.com/sigstore/sigstore-python/issues/1372
Makes the TSA request specify sha256 for the message digest, ~~since verification currently assumes sha256.~~ Verification shouldn't assume any specific algorithm, but I think for signing requests this library should specify an algorithm, for the sake of predictability. 
* TSA: Changed the Timestamp Authority requests to explicitly use sha256 for message digests.
> Specify sha256 in TSA request

- CHANGELOG.md
- test/unit/conftest.py
[Client support for Rekor V2: sigstore-python](https://github.com/sigstore/rekor-tiles/issues/289)
Resolves #1408
Fixes the fixtures that produce a `SigningContext`.
Tests: Updated the `staging` and `sign_ctx_and_ident_for_env` fixtures to use the new methods
for generating a `SigningContext`.
None
> use new SigningConfig generator in fixtures

- CHANGELOG.md
- sigstore/_internal/trust.py
- sigstore/_store/https%3A%2F%2Ftuf-repo-cdn.sigstore.dev/signing_config.v0.2.json
- sigstore/sign.py
- test/unit/internal/test_trust.py
* Change the SigningConfig API so that it returns actual clients (like RekorClient): this may seem unusual but makes sense because SigningConfig in practice must know which service/versions this client supports, this means the code is simplest if it directly returns correct clients (e.g. when rekor has two separate clients for v1 and v2). This allows keeping version, operator, selector mode, etc as SigningConfig implementation details: Otherwise some of those have to start leaking outside
* There is one exception to previous change: get_oidc_url() still returns string, not Issuer object. I could make this change as well to be consistent, it just requires a small refactor (because currently Issuer makes a http request on construction and that seems bad in general, but especially for …
> trust: Support operator field, support multiple services

- test/unit/conftest.py
This PR fixes the latest commit, the ambient credential tasks did not run and were skipped, leading to us missing out on some test cases running, and subsequently failing. I ran the workflow from my own fork where the tasks passed.
[success logs](https://github.com/SequeI/sigstore-python/actions/runs/15329826732/job/43133545034#step:6:113)
Apologies for this, the CI on the PR passed and I missed this issue in the original [PR](https://github.com/sigstore/sigstore-python/pull/1402)
The skipped tasks in the PR that failed during a push to main
```
test/unit/test_sign.py::test_sign_rekor_entry_consistent[staging] SKIPPED [ 44%]
test/unit/test_sign.py::test_sign_rekor_entry_consistent[production] SKIPPED [ 44%]
test/unit/test_sign.py::test_sct_verify_keyring_lookup_error[staging] SKIPPED [ …
```
> ci: ambient credential tests fix

- CHANGELOG.md
- sigstore/_internal/trust.py
- test/assets/trusted_root/trustedroot.v1.json
- test/assets/trusted_root/trustedroot.v1.local_tlog_ed25519_rekor-tiles.json
- test/unit/internal/test_trust.py
Currently verification fails immediately if trusted root contains any unsupported keys. I think it makes more sense to warn and continue as it is possible these keys are not required for verification.
Unfortunately I missed this case when I tested the multiple log support in #1350  :(
> trust: Fail less hard when unsupported keys are seen

- CHANGELOG.md
- sigstore/__init__.py
- sigstore/_internal/trust.py
- test/assets/trusted_root/trustedroot.v1.json
- test/unit/internal/test_trust.py
This is a backport of #1424 into 3.6.x series:
* This backport should make root-signing-staging update (with a ed25519 key) a little easier to manage
* Makes it more likely that all sigstore-python users have the fix once the same happens in production
Current main contains a lot of work (but not yet rekor v2 client integration) so I wouldn't like to release all of that now.
> Backport 1424, prepare 3.6.3 release

- .github/workflows/pin-requirements.yml
- CHANGELOG.md
- sigstore/__init__.py
* Merge changelog and version changes from 3.6.x branch
* workaround  the requirements pinning issue that was found in 3.6.3 release (#1426). I've tested this in my fork, looks ok
I'll file an issue to remove the workaround once pip-tools is fixed.
> Post 3.6.3 fixes

- .github/workflows/conformance.yml
- test/integration/sigstore-python-conformance
Fixes #821 by adding support for `--trusted-root` into our conformance client.
Annoyingly this requires writing a temporary (trust config) file on disk since that is what sigstore-python CLI needs instead of the provided trustedroot file.
This revealed a new issue #1442
> Conformance client update

- CHANGELOG.md
- sigstore/__init__.py
picks 3b1902666a06ac72d1f331138bfa8510d4f0b853
This is the last piece of the dependency/backport jigsaw 🙂
> chore: forward port changelog from 3.6.4

- sigstore/verify/verifier.py
- test/unit/verify/test_verifier.py
DRAFT While I think about it -- there's a few ways to handle this, not sure this is right.
Try to handle TSA timestamps and rekor v1 integrated time in a sensible manner:
* no special cases for when TSA timestamps are present
* require one verified time by default
* Only allow integrated time to be a verified time if entry is from rekor v1
* VERIFY_TIMESTAMP_THRESHOLD now refers to "number of verified times", not just TSA timestamps
* Tests use a rekor v1 bundle but expect it to be invalid if the timestamp is invalid -- but the integrated time is enough. Fix this by monkeypatching VERIFY_TIMESTAMP_THRESHOLD
Fixes #1488.
This would be back portable to make 3.x branch be able to verify newer bundles (that contain an "extra"  TSA timestamp)
> Clean up verified time handling

- CHANGELOG.md
- sigstore/verify/verifier.py
- test/unit/verify/test_verifier.py
This backports #1489 into 3.6.x: the point is to make sure that sigstore-python 3.6.x can verify a bundle created by sigstore-python 4.0 (if that bundle contains a rekor v1 entry and an additional timestamp). Currently the verification fails on staging  because
* signing code in 4.0 will include a timestamp in the bundle
* the timestamp certificate happens to use a keytype we do not support in 3.6.x (meaning the timestamp in the bundle is not considered valid).
* the verification code currently requires at least one timestamp to be valid (if any timestamps are included in the bundle) even if the integrated time should suffice 
This PR changes the last point: integrated time is enough.
I can add the release changes in this PR as well if there's nothing else for 3.6.5
> Backport verified time changes

- .github/workflows/pin-requirements.yml
pip-tools is now compatible with current pip
fixes #1428
> workflows: Remove pip-tools workaround

- CHANGELOG.md
- pyproject.toml
like I mentioned in previous pr, I don't think this absolutely necessary but if we're doing a 3.6.x release I think it's nice.
> Bump cryptography maximum version in 3.6.x
